addSbtPlugin("io.spray"         % "sbt-revolver"        % "$sbt_revolver_version$")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "$sbt_git_version$")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "$sbt_native_packager_version$")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "$sbt_scalafmt_version$")
addSbtPlugin("au.com.onegeek"   %% "sbt-dotenv"         % "$sbt_dotenv$")
